</div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-lg-2 memberside">
            <div>
                <?php require_once($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/nav_menu.php'); ?>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-10 text-center">
                    <div class="separator xs"></div>
                    <h4>Your Statistics</h4>
                </div>
                <div class="col-md-2">
                    <div class="separator sm"></div>
                </div>
            </div>
            <hr />
            <div class="separator "></div>

            <?php
                include($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/layout/stats/layout.stats_details.phtml');
            ?>

        </div>
        <div class="col-md-2 memberside d-none d-lg-block" style="padding: 0;">
            <div>
                <button class="btn bg-light p-2 right-profile-img" type="button" data-toggle="collapse" data-target="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
                    <div class="row">
                        <div class="col-xl-5">
                            <img src="<?=_SITE_PATH . '/uploads/avatar/' . md5((string) $_SESSION['user_info']['id']) . '/' . $_SESSION['user_info']['avatar']?>" alt="" class="rounded-circle" />
                        </div>
                        <div class="col-xl-7 pt-2 text-ellipsis">
                            Hi,
                            <?=$_SESSION['user_info']['first_name']?> <i class="icon-angle-down"></i>
                        </div>
                    </div>
                    <div id="collapse-1" class="collapse">
                        <div class="row">
                            <div class="col-12 mt-4">
                                <div class="text-right card-body bg-light text-center pt-0 " style="font-size: 16px">
                                    <a href="index.php?plugin=members&amp;op=logout" title="<?=_LOGOUT?>">
                                        <span class="icon-power-off"></span> Logout
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </button>
            </div>
        </div>
    </div>
</div>

