<div class="row-fluid">
    <div class="span8">
        <div class="pageheader">
            <h1 class="head">
                <?=$frm->reduce_words($album_info['name'], 5)?>
            </h1>
        </div>
    </div>
    <div class="span4">
        <div class="submit-top">
            <div style="text-align: right; margin: 10px;">
                <a class="btn btn-warning upload-images tipE" style="padding: 9px 5px 4px;" title="Upload Images" href="admin.php?plugin=pages&amp;addon=gallery&amp;op=upload_images&amp;id=<?=$id?>">
                    <span class="icon-pictures font30"></span>
                </a>
                <a class="btn btn-danger upload-images tipE" style="padding: 9px 5px 4px;" title="Add Youtube Videos" href="admin.php?plugin=pages&amp;addon=gallery&amp;op=add_youtube&amp;id=<?=$id?>">
                    <span class="icon-play font30"></span>
                </a>
            </div>
        </div>
    </div>
</div>
<hr />
<div id="contentwrapper" class="contentwrapper">
    <div class="gallerywrapper">
        <ul class="imagelist">
            <?php if(count($items_info)>0) {?>
                <?php foreach($items_info as $item) {?>
            <li id="item_<?=$item['id']?>">
                <div class="img" style="background: url(<?=($item['media'] != 'youtube' ? _SITE_PATH . '/uploads/gallery/' . $item['bid'] . '/thumb-' : '')?><?=$item['image']?>) no-repeat center center;  background-size: cover;">
                    <img src="images/blank.gif" alt="<?=$item['title']?>" />
                 </div>
                 <span class="hidden-phone">
                    <a href="admin.php?plugin=pages&amp;addon=gallery&amp;op=edit_images&amp;id=<?=$item['id']?>" class="name ajax"><?=substr($item['image'], 0, 20)?><?=(strlen($item['image'])>20) ? '...' : ''?></a>
                    <a href="admin.php?plugin=pages&amp;addon=gallery&amp;op=edit_images&amp;id=<?=$item['id']?>" class="edit ajax"></a>
                    <?php if($item['media'] != 'youtube') {?>
                    <a href="<?=_SITE_PATH?>/uploads/gallery/<?=$item['bid']?>/<?=$item['image']?>" class="view"></a>
                    <?php }?>
                    <a href="admin.php?plugin=pages&amp;addon=gallery&amp;op=delete_image&amp;id=<?=$item['id']?>" class="delete"></a>
                 </span>
            </li>
                <?php }?>
            <?php }?>
        </ul>
    </div>
</div>