<div class="photoEdit">
	<form id="editphoto" action="admin.php?plugin=pages&amp;addon=gallery" method="post" class="stdform quickform2">
    <input type="hidden" value="update_images" name="op" />
    <input type="hidden" value="<?=$item['id']?>" name="id" />
    	<h3>Edit Image Details</h3>
        <br />
        <div class="notifyMessage">Updated</div>
        <p>
            <label>Title: </label>
            <input type="text" value="<?=$item['title']?>" name="title" />
        </p>
        <p>
            <label>Description: </label>
            <textarea name="text" maxlength="200" style="width: 304px;"><?=$item['text']?></textarea>
        </p>
        <hr />
        <p class="action">
            <a href="#" class="cancel">Cancel</a>
        	<button class="submit radius2">Save</button> &nbsp;
        </p>
</form>
</div>