<form action="admin.php?plugin=system&amp;file=messages" method="post">
    <input type="hidden" value="update" name="op" />
    <input type="hidden" value="<?=$items_info[0]['id']?>" name="parent" />
    <input type="hidden" value="<?=$items_info[0]['sent_from']?>" name="sent_to" />
    <input type="hidden" value="<?=$administrator->admin_info['email']?>" name="sent_from" />
    <input type="hidden" value="<?=$items_info[0]['subject']?>" name="subject" />
    <input type="hidden" value="1" name="readed" />
    <input type="hidden" value="<?=time()?>" name="date" />
    <div class="row-fluid">
        <div class="span9">
            <div class="pageheader">
                <h1 class="head">
                    <?=$frm->reduce_words($items_info[0]['subject'], 10)?>
                </h1>
            </div>
        </div>
    </div>
    <?if(isset($_SESSION['error'])) {?>
        <div class="notibar msgerror">
            <a class="close"></a>
            <p><?=$_SESSION['error']?></p>
        </div>
        <?
        unset($_SESSION['error']);
    }
    ?>
    <div id="contentwrapper" class="contentwrapper">
    	<div class="widgetcontent">
            <ul class="recent_list">
                <?foreach($items_info as $item) {?>
                <li class="message new">
                    <div class="msg clearfix">
                            <div style="float: left;">
                                <?=$item['sender']['name']?>
                            </div>
                            <div style="float: right; width: 150px;" class="text-right">
                                <span class="icon-calendar-2 btn-icon"></span><?=$frm->format_sort_date($item['date'])?>
                            </div>
                    </div>
                    <div style="padding: 10px 20px; border-top: 1px solid #ddd;" >
                        <?=nl2br($item['text'])?>
                    </div>
                </li>
                <?}?>
            </ul>
        </div>
        <div class="enterMessage">
            <input type="text" value="<?=$_SESSION['temp_data']['message']?>" name="text" placeholder="Enter your message..." />
            <div class="sendBtn">
                <input type="submit" class="btn btn-small btn-primary" value="Send" />
            </div>
        </div>
    </div>
</form>