<table class="table">
	<colgroup span="4">
		<col style="width: 20%" />
		<col />
		<col style="width: 10%" />
		<col style="width: 30%" />
	</colgroup>
	<tr>
		<?foreach($table_headers as $header) {?>
		<td style="text-align: left;">
			<h5><?=$header?></h5>
		</td>
		<?}?>
	</tr>
	<?
	if(!$frm->empty_array($results)) {
		foreach($results as $result) {?>
			<tr>
				<td style="text-align: left;">
					<?=$result['element']?>
				</td>
				<td>
					<?=$result['url']?>
				</td>
				<td>
					<?=$result['visits']?>
				</td>
				<td>
					<div class="progress">
						<div class="bar" style="width: 100px; float: left; margin-right: 10px; margin-top: 5px;">
							<div style="width: <?=round(($result['visits'] / $result['CNT']) * 100)?>%;" class="value bluebar"></div>
						</div> <?=round(($result['visits'] / $result['CNT']) * 100, 2)?>%
					</div>
				</td>
			</tr>
		<?}?>
		<?} else {?>
		<tr>
			<td colspan="4" style="text-align: left;">
				No data to display here.
			</td>
		</tr>
	<?}?>
</table>