version: '3.5'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bodyologists
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: .
    volumes:
      - mysqldb_data_container:/var/lib/mysql

  bodyologists:
    build:
      context: .
      dockerfile: docker/bodyologists/Dockerfile
    depends_on:
      - mysqldb
    volumes:
      - .:/var/bodyologists
      - logs:/var/bodyologists/logs

  nginx:
    image: nginx:latest
    depends_on:
      - bodyologists
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/bodyologists
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/bodyologists.conf:/etc/nginx/conf.d/bodyologists.conf
      - logs:/var/bodyologists/logs

volumes:
  logs:
    driver: local
  mysqldb_data_container:
    driver: local
  certs:
    driver: local