<?if(isset($_SESSION['error'])) {?>
    <div class="alert-error" title="Error">
        <?=$_SESSION['error']?>
    </div>
<?
    unset($_SESSION['error']);
}
?>
<form action="admin.php?plugin=payments" method="post" class="stdform" class="validate-form">
    <input type="hidden" value="save" name="op" />
    <input type="hidden" value="0" id="save_and" name="save_and" />
    <input type="hidden" value="<?=$item['id']?>" name="id" />
    <input type="hidden" value="<?=time()?>" name="modified" />
    <input type="hidden" value="0" name="alive" />
    <div class="row-fluid">
        <div class="span9">
            <div class="pageheader">
                <h1 class="head">
                    <?=$meta['title']?>
                </h1>
            </div>
        </div>
        <div class="span3">
            <div class="submit-top">
                <div style="text-align: right; margin-right: 40px;">
                    <div style="position: relative; display: inline-block;">
                        <button class="btn btn-success tipN" style="margin-right: 10px;" type="submit" title="Submit Transation">
                            <span class="icon-disk"></span>
                        </button>
                        <button class="btn btn-warning tipN" type="reset" title="Undo Changes">
                            <span class="font20 icon-history"></span> 
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="contentwrapper" class="contentwrapper">
        <div class="row-fluid">
            <div class="span6">
                <p>
                    <label>
                        First Name: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['first_name']?>" name="first_name" class="required" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter the first name of the card owner.
                    </small>
                </p>
                <p>
                    <label>
                        Email: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['email']?>" name="email" class="required" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter person email address.
                    </small>
                </p>
            </div>
            <div class="span6">
                <p>
                    <label>
                        Last Name: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['last_name']?>" name="last_name" class="required" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter the last name of the card owner.
                    </small>
                </p>
                <p>
                    <label>
                        Phone: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['phone']?>" name="phone" class="required" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter person phone number.
                    </small>
                </p>
            </div>
        </div>
        <hr />
        <div class="row-fluid">
            <div class="span6">
                <p>
                    <label>
                        Amount to be Charge: 
                    </label>
                    <div class="field">
                        <div class="input-prepend" style="display: inline;">
                            <span class="add-on">$</span>
                            <input type="text" class="price-field" value="<?=$item['subtotal']?>" name="subtotal" class="required" />
                        </div>
                    </div>
                    <small class="desc">
                        Enter the amount to be changed.
                    </small>
                </p>
                <p>
                    <label>
                        Tax: 
                    </label>
                    <div class="field">
                        <label class="checkbox">
                            <input type="checkbox" value="1" <?=(!empty($item['charge_tax'])) ? 'checked="checked"' : ''?> name="charge_tax" /> Charge taxes if needed.
                        </label>
                    </div>
                    <small class="desc">
                        Mark this box to charge taxes within this transaction.
                    </small>
                </p>
                <div style="height: 3px;"></div>
                <p>
                    <label>
                        Card Type: 
                    </label>
                    <div class="field">
                        <?=$format_cc->get_cc_types('cc_type', $item['cc_type'], array('class' => 'uniformselect'))?>
                        <input type="hidden" value="Credit Card" name="payment_method" />
                    </div>
                    <small class="desc">
                        Select the type of card to be used.
                    </small>
                </p>
                <p>
                    <label>
                        Card Number: 
                    </label>
                    <div class="field">
                        <input type="text" value="<?=$item['cc_number']?>" name="cc_number" class="required" />
                    </div>
                    <small class="desc">
                        Enter the card number to be change.
                    </small>
                </p>
                <p>
                    <label>
                        Card Expiration Date: 
                    </label>
                    <div class="field">
                        <?=$format_cc->get_cc_exp_month('cc_month', $item['cc_month'], array('class' => 'uniformselect'))?>
                        <?=$format_cc->get_cc_exp_year('cc_year', $item['cc_year'], array('class' => 'uniformselect'))?>
                    </div>
                    <small class="desc">
                        Select card expiration date
                    </small>
                </p>
                <p>
                    <label>
                        Card CVC: 
                    </label>
                    <div class="field">
                        <input type="number" name="cc_cvv" value="<?=$item['cc_cvv']?>" class="required" style="width: 80px;" /> 
                    </div>
                    <small class="desc">
                        Enter the 3/4 numbers on the back of the card.
                    </small>
                </p>
            </div>
            <div class="span6">
                <p>
                    <label>
                        Country: 
                    </label>
                    <div class="field">
                        <?=$helper->get_countries('country', $bill_country, '', array('class' => 'uniformselect select-country', 'data-state' => 'state', 'data-holder' => 'state-area'))?>
                    </div>
                    <small class="desc">
                        Enter the 3/4 numbers on the back of the card.
                    </small>
                </p>
                <p>
                    <label>
                        Billing Address: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['address']?>" name="address" class="required" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter billing address associated with this card.
                    </small>
                </p>
                <p>
                    <label>
                        Suite/Apt: 
                    </label>
                    <div class="field">
                        <label>
                            <input type="text" value="<?=$item['address2']?>" name="address2" />
                        </label>
                    </div>
                    <small class="desc">
                        Enter billing address associated with this card.
                    </small>
                </p>
                <p>
                    <label>
                        City: 
                    </label>
                    <div class="field">
                        <input type="text" name="city" value="<?=$item['city']?>" class="required" />
                    </div>
                    <small class="desc">
                        Enter billing address associated city with this card.
                    </small>
                </p>
                <p>
                    <label>
                        State: 
                    </label>
                    <div class="field">
                        <div id="state-area">
                            <?=$helper->get_states("state", $item['state'], $bill_country, array('class' => 'uniformselect'))?>
                        </div>
                    </div>
                    <small class="desc">
                        Select Enter billing address state associated with this card.
                    </small>
                </p>
                <p>
                    <label>
                        Zip/Postal Code: 
                    </label>
                    <div class="field">
                        <input type="text" name="zip" value="<?=$item['zip']?>" class="required" />
                    </div>
                    <small class="desc">
                        Enter billing address zip/postal code associated with this card.
                    </small>
                </p>
            </div>
        </div>
    </div>
</form>