<div class="photoEdit">
	<form id="editphoto" action="admin.php?plugin=pages&amp;addon=slider" method="post" class="stdform quickform2">
    <input type="hidden" value="save" name="op" />
    	<h3>Configure Slider Properties</h3>
        <br />
        <div class="notifyMessage">Updated</div>
        <p>
            <label>Image Width: </label>
            <input type="text" value="<?=$slider_settings['width']?>" name="width" /> px
        </p>
        <p>
            <label>Image Height: </label>
            <input type="text" value="<?=$slider_settings['height']?>" name="height" /> px
        </p>
        <br />
        <p class="action">
        	<button class="submit radius2">Save Changes</button> &nbsp;
            <button class="cancel radius2">Close</button>
        </p>
        <br />
</form>
</div>