<?php
use App\Helper;
?>
<div class="row">
    <div class="col-md-4 px-5 layout-form-input">
        <input type="text" value="<?php echo Helper::encode($_GET['keyword']); ?>" name="keyword" class="form-control form-control-lg input-field-text upper" placeholder="Type Keyword" />
    </div>
    <div class="col-md-4 px-5 layout-form-input">
        <input type="text" value="<?php echo Helper::encode($_GET['location']); ?>" name="location" class="form-control form-control-lg input-field-text upper" placeholder="City, Zip or State" />
    </div>
    <div class="col-md-4 px-5 form-submit-btn-container">
        <button class="btn btn-danger btn-lg form-submit-btn" type="submit">
            Search
        </button>
    </div>
</div>

<?php
$advanced_fields = [
    'category',
    'to_do',
    'price_range_enabled',
    'distance_enabled',
    'reset'
];
$is_advanced_search = (!empty(array_intersect(array_keys(array_filter($_GET)), $advanced_fields)));
?>

<div class="row">
    <div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4 mt-4 text-center">
        <button
            class="btn btn-success mb-4 p-3"
            style="width: 80%; margin: 0 auto; font-size: 1.25rem;"
            data-toggle="collapse"
            data-target="#advanced_search"
            aria-expanded=<?=$is_advanced_search ? 'true':'false'?> >
            Advanced Filters <i class="icon-angle-down float-right"></i>
        </button>
    </div>
</div>
<div class="row">
    <div class="col-1"></div>
    <div class="col-10 px-5 layout-form-filters-container">
        <div class="<?=$is_advanced_search ? 'collapse show':'collapse'?> bg-light py-3 mx-4 rounded" id="advanced_search">
            <div class="row mb-3">
                <div class="col-md-1"></div>
                <div class="col-md-5 layout-form-filter-divider">
                    <select name="category" class="form-control form-control-lg">
                        <option value="">CATEGORY</option>
                        <option <?=($_GET['category'] == 'Health') ? ' selected="selected"' : ''?> value="Health">Health Deals</option>
                        <option <?=($_GET['category'] == 'Fitness') ? ' selected="selected"' : ''?> value="Fitness">Fitness Deals</option>
                        <option <?=($_GET['category'] == 'Beauty') ? ' selected="selected"' : ''?> value="Beauty">Beauty Deals</option>
                    </select>
                </div>
                <div class="col-md-5">
                    <select name="to_do" class="form-control form-control-lg" id="thistodo" <!--onchange='checkvalue(this.value)-->'>
                    <option value="">THINGS TO DO</option>
                    <option value="Today" <?=($_GET['to_do'] == 'Today') ? ' selected="selected"' : ''?>>Today</option>
                    <option value="Tomorrow" <?=($_GET['to_do'] == 'Tomorrow') ? ' selected="selected"' : ''?>>Tomorrow</option>
                    <option value="This week" <?=($_GET['to_do'] == 'This week') ? ' selected="selected"' : ''?>>This week</option>
                    <option value="This weekend" <?=($_GET['to_do'] == 'This weekend') ? ' selected="selected"' : ''?>>This weekend </option>
                    <option value="This month" <?=($_GET['to_do'] == 'This month') ? ' selected="selected"' : ''?>>This month</option>
                    <option value="Next Month" <?=($_GET['to_do'] == 'Next Month') ? ' selected="selected"' : ''?>>Next Month</option>
                    <!--                            <option value="pick">Pick a Date</option>-->
                    </select>
                    <!--                        <input type="text" name="to_do" placeholder="mm/dd/yyyy" id="todo" class="datepicker form-control form-control-lg" style="display: none; ">-->
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-1"></div>
                <div class="col-md-5 layout-form-filter-divider">
                    <div>
                        <button class="form-control form-control-lg text-left" type="button" id="dropPriceRange" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            PRICE RANGE
                        </button>
                        <div class="dropdown-menu p-3" aria-labelledby="dropPriceRange" style="width: 90%;">
                            <label class="checkbox-inline range-filters-label" style="padding-left: 5px; width: 90%;">
                                ENABLE PRICE FILTERING
                            </label>
                            <input name="price_range_enabled" class="form-control checkbox-inline"
                                   type="checkbox"
                                   style="width: auto; box-shadow: none; float: left; margin-top: 5px;"
                                <?= isset($_GET['price_range_enabled']) ? 'checked' : '' ?>
                            >
                            <input type="text" class="js-range-slider" name="price_range" value="" />
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <button class="form-control form-control-lg text-left" type="button" id="dropDistance" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        DISTANCE
                    </button>
                    <div class="dropdown-menu p-3" aria-labelledby="dropDistance" style="width: 90%">
                        <label class="checkbox-inline range-filters-label" style="padding-left: 5px; width: 90%;">
                            ENABLE DISTANCE FILTERING
                        </label>
                        <input name="distance_enabled" class="form-control checkbox-inline"
                               type="checkbox"
                               style="width: auto; box-shadow: none; float: left; margin-top: 5px;"
                            <?= isset($_GET['distance_enabled']) ? 'checked' : '' ?>
                        >
                        <input type="text" class="js-distance-slider" name="distance" value="" />
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    <button type="button" class="btn btn-danger btn-lg advanced-form-reset-button">
                        Reset
                    </button>
                </div>
                <div class="col-md-5"></div>
            </div>
        </div>
    </div>
    <div class="separator"></div>
</div>
<script>
    $(document).ready(function(){
        $(".advanced-form-reset-button").click(function (e) {
            var keyword = $('input[name="keyword"]').val();
            var location = $('input[name = location]').val();

            window.location.href = "search/deals?keyword=" + keyword +"&location=" + location + "&reset=1";
        });
    });
</script>