DELIMITER ;;
DROP FUNCTION IF EXISTS ANY_VALUE_IN_RANGE;;
CREATE FUNCTION `ANY_VALUE_IN_RANGE`(`collection` JSON, `min` INT, `max` INT) RETURNS BOOL
READS SQL DATA
BEGIN
DECLARE i INTEGER DEFAULT 0;
DECLARE entry FLOAT;

   WHILE i < JSON_LENGTH(collection) DO
   	SET entry = JSON_EXTRACT(collection,CONCAT('$[',i,']'));

   	IF entry BETWEEN `min` AND `max` THEN
   		RETURN TRUE;
	   END IF;

	   SELECT i + 1 INTO i;

	END WHILE;

	RETURN FALSE;

END ;;
DELIMITER ;