ALTER TABLE `wde_deals`
    CHANGE COLUMN `id` `id` INT(10) NOT NULL AUTO_INCREMENT FIRST,
    CHANGE COLUMN `owner` `owner` INT(10) NULL AFTER `id`,
    CHANGE COLUMN `category` `category` VARCHAR(160) NULL DEFAULT '' COLLATE 'utf8_general_ci' AFTER `owner`,
    CHANGE COLUMN `title` `title` VARCHAR(255) NULL COLLATE 'utf8_general_ci' AFTER `category`,
    CHANGE COLUMN `url` `url` VARCHAR(255) NULL COLLATE 'utf8_general_ci' AFTER `title`,
    CHANGE COLUMN `purchase_link` `purchase_link` TEXT(65535) NULL COLLATE 'utf8_general_ci' AFTER `url`,
    CHANGE COLUMN `start_date` `start_date` DATE NULL AFTER `purchase_link`,
    CHANGE COLUMN `end_date` `end_date` DATE NULL AFTER `start_date`,
    CHANGE COLUMN `reg_price` `reg_price` DECIMAL(10,2) NULL DEFAULT '0.00' AFTER `end_date`,
    CHANGE COLUMN `discount` `discount` DECIMAL(10,2) NULL DEFAULT '0.00' AFTER `reg_price`,
    CHANGE COLUMN `address` `address` VARCHAR(255) NULL COLLATE 'utf8_general_ci' AFTER `discount`,
    CHANGE COLUMN `city` `city` VARCHAR(150) NULL COLLATE 'utf8_general_ci' AFTER `address`,
    CHANGE COLUMN `state` `state` VARCHAR(150) NULL COLLATE 'utf8_general_ci' AFTER `city`,
    CHANGE COLUMN `zipcode` `zipcode` VARCHAR(150) NULL COLLATE 'utf8_general_ci' AFTER `state`,
    CHANGE COLUMN `text` `text` TEXT(65535) NULL COLLATE 'utf8_general_ci' AFTER `zipcode`,
    CHANGE COLUMN `policies` `policies` TEXT(65535) NULL COLLATE 'utf8_general_ci' AFTER `text`,
    CHANGE COLUMN `notes` `notes` TEXT(65535) NULL COLLATE 'utf8_general_ci' AFTER `policies`,
    CHANGE COLUMN `active` `active` INT(1) NULL DEFAULT '0' AFTER `notes`,
    CHANGE COLUMN `visits` `visits` BIGINT(19) NULL DEFAULT '0' AFTER `active`,
    CHANGE COLUMN `date` `date` DATETIME NULL AFTER `visits`,
    CHANGE COLUMN `modified` `modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `date`;