ALTER TABLE `wde_blog`
    CHANGE COLUMN `category` `category` VARCHAR(255) NULL COLLATE 'utf8_general_ci' AFTER `id`,
    CHANGE COLUMN `poster` `poster` VARCHAR(128) NULL COLLATE 'utf8_general_ci' AFTER `category`,
    CHANGE COLUMN `title` `title` VARCHAR(255) NULL COLLATE 'utf8_general_ci' AFTER `poster`,
    CHANGE COLUMN `url` `url` VARCHAR(225) NULL COLLATE 'utf8_general_ci' AFTER `title`,
    CHANGE COLUMN `text` `text` LONGTEXT NULL COLLATE 'utf8_general_ci' AFTER `url`,
    CHANGE COLUMN `extras` `extras` TINYTEXT NULL COLLATE 'utf8_general_ci' AFTER `text`,
    CHANGE COLUMN `meta_title` `meta_title` VARCHAR(68) NULL COLLATE 'utf8_general_ci' AFTER `extras`,
    CHANGE COLUMN `meta_description` `meta_description` TEXT NULL COLLATE 'utf8_general_ci' AFTER `meta_title`,
    CHANGE COLUMN `tags` `tags` TINYTEXT NULL COLLATE 'utf8_general_ci' AFTER `meta_description`,
    CHANGE COLUMN `allow_comments` `allow_comments` TINYINT(1) NULL DEFAULT '0' AFTER `tags`,
    CHANGE COLUMN `featured` `featured` TINYINT(1) NULL DEFAULT '0' AFTER `allow_comments`,
    CHANGE COLUMN `rates` `rates` BIGINT(20) NULL DEFAULT '0' AFTER `featured`,
    CHANGE COLUMN `votes` `votes` INT(10) NULL DEFAULT '0' AFTER `rates`,
    CHANGE COLUMN `active` `active` TINYINT(1) NULL DEFAULT '0' AFTER `votes`,
    CHANGE COLUMN `date` `date` DATETIME NULL AFTER `active`,
    CHANGE COLUMN `modified` `modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `date`,
    CHANGE COLUMN `visits` `visits` BIGINT(20) NULL DEFAULT '0' AFTER `modified`,
    CHANGE COLUMN `lang` `lang` VARCHAR(8) NULL DEFAULT 'english' COLLATE 'utf8_general_ci' AFTER `visits`,
    CHANGE COLUMN `alive` `alive` TINYINT(1) NULL DEFAULT '1' AFTER `lang`;