<?php if(isset($_SESSION['error'])) {?>
    <div class="alert-error" title="Error">
        <?=$_SESSION['error']?>
    </div>
    <?php
    unset($_SESSION['error']);
}
?>

<div class="pageheader">
    <h1 class="head">
        Clients Summary
    </h1>
</div>
<br clear="all" />

<div class="summary-bar">
    <a href="#" class="reload tipS" title="Reload" onclick="window.location.href = window.location.href; return false;">
        <span class="icon-redo"></span>
    </a>
    <a class="tipS" title="Add New" href="admin.php?plugin=members&amp;op=edit">
        <span class="icon-plus-2"></span>
    </a>
    <a class="tipS" title="Settings" href="admin.php?plugin=members&amp;op=settings">
        <span class="icon-cog-3"></span>
    </a>
    <a class="tipS" title="Export" href="admin.php?plugin=members&amp;op=export">
        <span class="icon-download-2"></span>
    </a>
</div>
<div class="search-area">
    <form action="#">
        <input type="text" id="search-area" data-url="index.php?plugin=members" value="" name="q" placeholder="Search..." />
    </form>
</div>
<div id="contentwrapper" class="contentwrapper">    
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col />
            <col style="width: 160px;" />
            <col style="width: 100px;" />
            <col style="width: 150px;" />
            <col style="width: 10px;" />
        </colgroup>
        <thead>
            <tr>
                <th>Client</th>
                <th class="hidden-phone">Information</th>
                <th class="hidden-phone">Access</th>
                <th class="hidden-phone">Created/Last Seen</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php
            if(count($items_info)>0)
            {
            	foreach($items_info as $item)
            	{
                    include($_SERVER['DOCUMENT_ROOT'] . _SITE_PATH . '/plugins/members/admin/layout/layout.members.list.phtml');
                }
            }
            ?>
        </tbody>
    </table>
</div>
<div id="ajax-load-more-content" class="well hide" data-url="admin.php?plugin=members&amp;op=more">
    <img src="images/loaders/loader6.gif" alt="Loading" />
</div>