</div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-lg-2 memberside">
            <div>
                <?php
                use App\Helper;
                use App\Html;
                use Plugins\Events\Classes\Events;

                require_once($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/nav_menu.php'); ?>
            </div>
        </div>
        <div class="col-md-8 ">
           <div class="row">
                <div class="col-12 text-center">
                    <div class="separator xs"></div>
                    <h4 role="heading">Create Event</h4>
                </div>
            </div> 

            <form action="members/events/add" method="post" class="validate-form">
                <input type="hidden" value="<?php echo Helper::encode($item['id']); ?>" name="id" />
                <input type="hidden" value="<?php echo Helper::encode($item['url']); ?>" name="url" />
                <div class="row">
                    <div class="col-md-8">
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Title:</label>
                                <input type="text" value="<?php echo Helper::encode($item['title']); ?>" name="title" class="required form-control " />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-12">
                                <label>Description:</label>
                                <textarea name="text" class="form-control" minlength="50" maxlength="1500"  rows="5" placeholder="Describe your event"><?=$item['text']?></textarea>
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-6">
                                <label>Start Date:  </label>
                                <input type="date" value="<?php echo Helper::encode($item['start_date']); ?>" name="start_date" class="datepick form-control " />
                            </div>
                            <div class="col-md-6">
                                <label>End Date:  </label>
                                <input type="date" value="<?php echo Helper::encode($item['end_date']); ?>" name="end_date" class="datepick form-control " />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-6">
                                <label>Start Time:  </label>
                                <input type="time" value="<?php echo Helper::encode($item['start_time']); ?>" name="start_time" class="timepick form-control " />
                            </div>
                            <div class="col-md-6">
                                <label>End time:  </label>
                                <input type="time" value="<?php echo Helper::encode($item['end_time']); ?>" name="end_time" class="timepick form-control " />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Location / Address:</label>
                                <input type="text" value="<?php echo Helper::encode($item['address']); ?>" name="address" class="form-control" placeholder="" />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>URL for purchase ticket or booking event:</label>
                                <input type="url" value="<?php echo Helper::encode($item['purchase_link']); ?>" name="purchase_link" class="form-control" placeholder="e.g www.yoursite.com/special-offer" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Organizer:</label>
                                <input type="text" value="<?php echo Helper::encode((!empty($item['seller'])) ? $item['seller'] : $_SESSION['user_info']['company']); ?>" name="seller" class="form-control" />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-12" id="upload-area">
                                <label>Event Image:</label>
                                <div class="col-12" id="cropper-container" style="overflow: hidden">
                                    <div id="cropContainerModal">
                                        <div id="img-holder" class="avatar avatar-big" title="Please use a photo with light/clear background. Also, respect license/copyright."
                                             onclick="$('i.cropControlUpload').click();"
                                             style="background-image: url(<?= Events::getFirstImageURL($item['id']) ?>); margin-top: 0px;">
                                            <img src="images/blank.gif">
                                        </div>
                                    </div>

                                    <!-- ==================================== -->
                                    <!--      I M A G E   C R O P P E R       -->
                                    <!-- ==================================== -->
                                    <link rel="stylesheet" href="/croppic/croppic.css">
                                    <style>
                                        #img-holder, .croppedImg {
                                            width: 100%;
                                            height: 100%;
                                        }

                                        #cropContainerModal {
                                            width: 720px;
                                            height: 480px;
                                            display: contents;
                                        }

                                        img {
                                            /*max-height: none;
                                            max-width: none;*/
                                        }
                                        .cropContainerModal_imgUploadForm {
                                            display: none;
                                        }
                                    </style>
                                    <script src="/croppic/croppic.js"></script>
                                    <script>
                                        const croppicContainerModalOptions = {
                                            cropData: {
                                                'owner': '<?=$_SESSION['user_info']['id']?>',
                                                'folder_name': 'events',
                                                'id': '<?=$item['id']?>',
                                                'confirm_field': '1'
                                            },
                                            uploadUrl: 'uploads.php?op=cropImage',
                                            cropUrl: 'uploads.php?op=saveEventImage',
                                            modal: true,
                                            imgEyecandyOpacity: 0.4,
                                            defaultImg: '<?= Events::getFirstImageURL($item['id']) ?>',
                                            loaderHtml: '<div class="loader bubblingG"><span id="bubblingG_1"></span><span id="bubblingG_2"></span><span id="bubblingG_3"></span></div> ',
                                            onAfterImgCrop: function () {
                                                $('#img-holder').attr('src', cropContainerModal.url);
                                            },
                                            onReset: function () {
                                                var container = $('#cropper-container');
                                                if (cropContainerModal) {
                                                    cropContainerModal.destroy();
                                                }
                                                container.html(
                                                    '<div id="cropContainerModal">' +
                                                    '    <div id="img-holder" class="avatar avatar-big" ' +
                                                    '        title="Click here to upload an image" onclick=\"$(\'i.cropControlUpload\').click()\" ' +
                                                    '        style="background-image: url(\'<?= Events::getFirstImageURL($item['id']) ?>\'); width: 200px; height: 120px">' +
                                                    '        <img src="images/blank.gif">' +
                                                    '    </div>' +
                                                    '</div>'
                                                );
                                            }
                                        };
                                        var cropContainerModal = new Croppic('cropContainerModal', croppicContainerModalOptions);
                                        $('i.cropControlUpload').hide();
                                    </script>
                                    <!-- ==================================== -->
                                    <!-- ==================================== -->
                                </div>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Category: </label>
                                <select name="category" class="required form-control form-control-lg">
                                    <option value="">Select a Category</option>
                                        <option <?=($item['category'] == 'Health') ? ' selected="selected"' : ''?> value="Health">
                                            Health
                                        </option>
                                        <option <?=($item['category'] == 'Fitness') ? ' selected="selected"' : ''?> value="Fitness">
                                            Fitness
                                        </option>
                                        <option <?=($item['category'] == 'Beauty') ? ' selected="selected"' : ''?> value="Beauty">
                                            Beauty
                                        </option>
                                </select>
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Cost:</label>
                                <input type="text" value="<?php echo Helper::encode($item['price']); ?>" name="price" class="form-control " placeholder="Cost" />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>City:</label>
                                <input type="text" value="<?php echo Helper::encode($item['city']); ?>" name="city" class="form-control " placeholder="City" />
                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>State:</label>
                                <?php
                                echo Html::renderDropdownWithKeys(
                                    'state',
                                    Helper::getStatesList(),
                                    $item['state'],
                                    'form-control required')
                                ?>

                            </div>
                        </div>
                        <div class="separator sm"></div>
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <label>Zipcode:</label>
                                <input type="text" value="<?php echo Helper::encode($item['zipcode']); ?>" name="zipcode" class="form-control " placeholder="Zip Code" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="separator "></div>
                    <div class="col-md-3">
                        <a href="members/events" class="btn btn-success btn-lg">
                            Cancel
                        </a>
                    </div>
                    <div class="col-md-6"></div>
                    <div class="col-md-3">
                        <button class="btn btn-primary btn-lg" type="submit">
                            Publish
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <script type="text/javascript" src="js/plugins/jquery.html5.upload.js"></script>
        <div class="col-md-2 memberside d-none d-lg-block">
            <div class="row">
                <button class="btn bg-light p-2 right-profile-img" type="button" data-toggle="collapse" data-target="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
                    <div class="row">
                        <div class="col-xl-5">
                            <img src="<?=_SITE_PATH . '/uploads/avatar/' . md5((string) $_SESSION['user_info']['id']) . '/' . $_SESSION['user_info']['avatar']?>" alt="" class="rounded-circle" />
                        </div>
                        <div class="col-xl-7 pt-2 text-ellipsis">
                            Hi, <?=$_SESSION['user_info']['first_name']?>
                        </div>
                    </div>
                </button>
            </div>
        </div>
    </div>
</div>


