<?require_once($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/nav_menu.php')?>
<?=_MEMBERS_ADDRESS_TEXT?>
<form action="index.php?plugin=members&amp;file=address" method="post" class="form-horizontal validate-form">
	<input type="hidden" value="save" name="op" />
    <input type="hidden" value="<?=$address['id']?>" name="id" />
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6">
            <h3><?=_MEMBERS_REGISTRATION_PERSONAL_DETAILS?></h3>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <input type="text" name="first_name" value="<?=(!empty($_SESSION['address']['first_name'])) ? $_SESSION['address']['first_name'] : $address['first_name']?>" class="required form-control" placeholder="<?=_FIRST_NAME?>" />
                </div>
                <div class="col-md-6 col-sm-6">
                    <input type="text" name="last_name" value="<?=(!empty($_SESSION['address']['last_name'])) ? $_SESSION['address']['last_name'] : $address['last_name']?>" class="required form-control" placeholder="<?=_LAST_NAME?>" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <input type="tel" name="phone" value="<?=(!empty($_SESSION['address']['phone'])) ? $_SESSION['address']['phone'] : $address['phone']?>" class="required form-control" placeholder="<?=_PHONE?>" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?if(!empty($address['add_type'])) {?>
                        <input type="hidden" value="1" name="add_type" />
                    <?} else {?>
                        <label>
                            <input type="checkbox" value="1" name="add_type" /> <?=_MEMBERS_ADDRESS_MAKE_DEFAULT?>
                        </label>
                    <?}?>
                </div>
            </div>
        </div>
        <hr class="hidden-lg hidden-md" />
        <div class="col-md-6">
            <h3><?=_MEMBERS_ADDRESS_ADD_INFO?></h3>
            <div class="row">
                <div class="col-md-12">
                    <?=$helper->get_countries("country", (!empty($_SESSION['address']['country'])) ? $_SESSION['address']['country'] : $address['country'], '', array('class' => 'country form-control'))?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9 col-sm-9">
                    <input type="text" name="address" value="<?=(!empty($_SESSION['address']['address'])) ? $_SESSION['address']['address'] : $address['address']?>" class="required form-control" placeholder="<?=_ADDRESS?>" />
                </div>
                <div class="col-md-3 col-sm-3">
                    <input type="text" name="suite" value="<?=(!empty($_SESSION['address']['suite'])) ? $_SESSION['address']['suite'] : $address['suite']?>" class="form-control" placeholder="<?=_ADDRESS_APT?>" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-5 col-sm-5">
                    <input type="text" name="city" value="<?=(!empty($_SESSION['address']['city'])) ? $_SESSION['address']['city'] : $address['city']?>" class="required form-control" placeholder="<?=_CITY?>" />
                </div>
                <div class="col-md-4 col-sm-4">
                    <?=$helper->get_states("state", (!empty($_SESSION['address']['state'])) ? $_SESSION['address']['state'] : $address['state'], (!empty($_SESSION['address']['country'])) ? $_SESSION['address']['country'] : $address['country'], array('class' => 'state form-control'))?>
                </div>
                <div class="col-md-3 col-sm-3">
                    <input type="text" name="zipcode" value="<?=(!empty($_SESSION['address']['zipcode'])) ? $_SESSION['address']['zipcode'] : $address['zipcode']?>" class="required form-control" placeholder="<?=_ZIP?>" />
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="text-right">
        <button class="btn btn-lg btn-primary" type="submit">
            <?=_SAVE_INFO?>
        </button>
    </div>
</form>