<div class="disclaimer">
    <p>This email has been generated automatically from <?= $config('sitename') ?>. PLEASE DO NOT RESPOND TO THIS EMAIL.
        If you need help or more information about this or any other of our services
        please <a href="mailto:<?= $config('contactemail') ?>">click here</a> to contact our support team.
    </p>
    <p><strong><?= $config('sitename') ?> Feedback</strong></p>
    <p>We'll love to hear from you, please <a href="<?= $config('siteurl') ?>">click here</a> to leave us a feedback.</p>
    <p>Copyright <?=date('Y')?> <?= $config('sitename') ?>. All rights reserved </p>
</div>