<head>
    <title> <?= $title ?> </title>
    <style type="text/css">
        body {
            font-size: 12px;
            font-family: "Lucida Grande", "Lucida Sans Unicode", Helvetica, Arial, Verdana, sans-serif;
        }
        h1 {
            color: #000000;
            font-size: 50px;
            marign: 0;
            padding: 0;
            line-height: 50px;
            text-transform: uppercase;
        }
        div.header {
            padding: 10px;
            margin-bottom: 10px;
        }
        div.footer {
            padding: 10px;
            margin-top: 10px;
        }
        div.disclaimer {
            font-size: 11px;
            margin-top: 10px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
        }
    </style>
</head>