<html>
    <head>
        <style type="text/css">
            body {
                font-size: 12px;
                font-family: "Lucida Grande", "Lucida Sans Unicode", Helvetica, Arial, Verdana, sans-serif;
            }
            h1 {
                color: #000000;
                font-size: 50px;
                marign: 0;
                padding: 0;
                line-height: 50px;
                text-transform: uppercase;
            }
            div.header { 
                padding: 10px;
                margin-bottom: 10px;
            }
            div.footer { 
                padding: 10px;
                margin-top: 10px;
            }
            div.disclaimer {
                font-size: 11px;
                margin-top: 10px;
                padding-top: 10px;
                border-top: 1px solid #ddd;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <?if(file_exists($_SERVER['DOCUMENT_ROOT'] . _SITE_PATH . '/images/email-logo.png')) {?>
            <a href="http://<?=$this->site_domain() . _SITE_PATH?>">
                <img src="http://<?=$this->site_domain() . _SITE_PATH?>/images/email-logo.png" alt="<?=$this->config['contactname']?>" />
            </a>
            <?} else {?>
                <h1><?=$this->config['contactname']?></h1>
            <?}?>
        </div>
        <p><?=_MEMBERS_EMAIL_LOST_PASSWORD_TEXT_TOP?> <?=$item_info['first_name']?></p>
        <p><?=_MEMBERS_EMAIL_LOST_PASSWORD_BODY_TOP?></p>
        <p>http://<?=$this->site_domain() . _SITE_PATH ?>/members/reset/?d=<?=$this->encode_var(array('email' => $data['email'], 'cc' => $cc, 'tt' => $tt))?></p>
        <p><?=_MEMBERS_EMAIL_LOST_PASSWORD_BODY_MIDDLE?></p>
        <p><?=_MEMBERS_EMAIL_LOST_PASSWORD_BODY_BOTTOM?></p>
        <div class="disclaimer">
            <p>This email has been generated automatically from <?=$this->config['contactname']?>. PLEASE DO NOT RESPOND TO THIS EMAIL. If you need help or more information about this or any other of our services please <a href="mailto:<?=$this->config['contactemail']?>">click here</a> to contact our support team.</p>
            <p><strong><?=$this->config['contactname']?> Feedback</strong></p>
            <p>We'll love to hear from you, please <a href="http://<?=$this->site_domain() . _SITE_PATH?>/">click here</a> to leave us a feedback.</p>
            <p>Copyright <?=date('Y')?> <?=$this->config['contactname']?>. All rights reserved </p>
            Sent from <?=$this->config['contactname']?> on <?=date('l, F jS Y')?> to <?=$data['email']?>
        </div>
    </body>
</html>