<?php
use App\Helper;

$result = $helper->sql_get_one('customer_services', ['fee'], "`user_id` = {$item['id']}", 'fee ASC');
$serviceFee = !empty($result) ? $result['fee'] : 0;
$distanceLabel = 'Distance: ';
if (!empty($item['distance_in_km'])) {
    $distanceLabel .= round($item['distance_in_km'] * 1.609344, 1) . 'mi';
} else {
    $distanceLabel .= 'n/a';
}

$categories = Helper::getCategoriesList();
$categoryLabel = $categories[$item['main_category']][ucfirst($item['category'])];
?>
<div class="card p-3 mb-3 search-list border-0 d-block d-md-none" >
    <div class="row">
        <div class="col-md-3">
            <a href="<?=$item['url']?>">
               <img class="card-img-top" src="<?=(!empty($item['avatar']) ? _SITE_PATH . '/uploads/avatar/' . md5((string) $item['id']) . '/' . $item['avatar'] : _SITE_PATH . '/uploads/thumb-silhouette.jpg')?>" alt="<?=$item['full_name']?>">
            </a>            
        </div>
        <div class="col-md-6 pt-2">
            <div class="name">
                <h5 class="elipsis"><?=$item['full_name']?>
                    <small class="d-block"><?=ucwords($categoryLabel)?> </small>
                </h5>
            </div>   
            <div class="separator xs"></div>
            <div class="bio">
                <?php
                $i = 0;
                $specialties = [];
                foreach($item['extra']['training']['certification'] as $specialty) {
                    $specialties[] = $specialty;
                    $i++;
                    if ($i > 3) {
                        break;
                    }
                }
                ?>
                Specialties:  <?= implode(', ', $specialties) ?><br>
                Starting at: $<?=$serviceFee?> <br>
            </div>
        </div>
        <div class="col-md-3 pt-2 text-center">
            <?=$item['company']?> <br>
            <?=$distanceLabel?> <br>
            <?=$item['city']?>, <?=$item['state']?> <br>

            <div class="separator "></div>
            <a href="<?=$item['url']?>" class="btn btn-light btn-block">
                VIEW PROFILE
            </a>            
        </div>
    </div>
</div>
<div class="card p-3 mb-3 search-list border-0 d-none d-md-block" >
    <div class="row">
        <div class="col-md-3">
            <a href="<?=$item['url']?>">
                <img class="card-img-top" src="<?=(!empty($item['avatar']) ? _SITE_PATH . '/uploads/avatar/' . md5((string) $item['id']) . '/' . $item['avatar'] : _SITE_PATH . '/uploads/thumb-silhouette.jpg')?>" alt="<?=$item['full_name']?>">

            </a>
        </div>
        <div class="col-md-9 pt-2">
            <div class="row">
                <div class="col-md-6">
                    <div class="name">
                        <h5 class="elipsis"><?=$item['full_name']?>
                            <small class="d-block"><?=ucwords($categoryLabel)?> </small>
                        </h5>
                    </div>
                </div>
                <div class="col-md-6" style="text-align: end; font-size: 1.2rem;">
                    <?=$item['company']?> <br>
                    <?=$distanceLabel?> <br>
                    <?=$item['city']?>, <?=$item['state']?> <br>
                </div>
            </div>
            <div class="separator "></div>
            <div class="row">
                <div class="col-md-10" style="font-size: 1.3rem">
                    <?php
                    $i = 0;
                    $specialties = [];
                    foreach($item['extra']['training']['certification'] as $specialty) {
                        $specialties[] = $specialty;
                        $i++;
                        if ($i > 3) {
                            break;
                        }
                    }
                    ?>
                    Specialties:  <?= implode(', ', $specialties) ?><br>

                </div>
            </div>
            <div class="separator "></div>
            <div class="row">
                <div class="col-md-7">
                    Starting at: $<?=$serviceFee?> <br>
                </div>
                <div class="col-md-5">
                    <a href="<?=$item['url']?>" class="btn btn-light btn-block">
                        VIEW PROFILE
                    </a>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- <div class="card member-list d-none">
    <div class="img-area">
        <a href="<?=$item['url']?>">
            <img class="card-img-top" src="<?=(!empty($item['avatar']) ? _SITE_PATH . '/uploads/avatar/' . md5((string) $item['id']) . '/thumb-' . $item['avatar'] : _SITE_PATH . '/uploads/thumb-silhouette.jpg')?>" alt="<?=$item['full_name']?>">
        </a>
        <div class="name">
            <h5 class="elipsis"><?=$item['full_name']?></h5>
        </div>
        <div class="bio">
            <?=$helper->reduce_text($item['bio'], 50)?>
        </div>
        
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row">
                <div class="col-12 text-capitalize text-center">
                    <small class="xs text-uppercase">category</small>
                    <?=$item['main_category']?> | <?=$item['category']?>
                </div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-12 text-capitalized text-center">
                    <small class="xs text-uppercase">location</small>
                    <?=$item['city']?> <?=(!empty($item['state']) ? ', ' . $item['state'] : '')?>
                </div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="text-right">
                <a href="<?=$item['url']?>" class="btn btn-warning btn-block">
                    Details
                </a>
            </div>
        </li>
    </ul>
</div>
 -->