<div class="separator "></div>
<h1><?=_MEMBERS_PASSWDRESET_HEADER?></h1>
<p><?=_MEMBERS_PASSWDRESET?></p>
<div class="separator "></div>
<form action="index.php?plugin=members&amp;op=go_reset_password" method="post" class="form-horizontal validate-form">
	<input type="hidden" name="email" value="<?=$data['email']?>" />
	<input type="hidden" name="cc" value="<?=$data['cc']?>" />
	<input type="hidden" name="tt" value="<?=$data['tt']?>" />
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
			<input type="password" name="passwd" id="passwd" value="" class="form-control form-control-lg required" placeholder="<?=_ENTER?> <?=_A?> <?=_MEMBERS_PASSWDRESET_NEW_PASSWD?>" />
		</div>
	</div>
	<div class="separator xs"></div>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4">
	    	<input type="password" name="passwd2" id="passwd2" value="" class="form-control form-control-lg required" placeholder="<?=_PLEASE?> <?=_MEMBERS_PASSWDRESET_CONFIRM_PASSWD?>" />
	    	<span class="help-block text-center"><small><?=_MEMBERS_FORGOTTEN_MORE_HELP?></small></span>
		</div>
	</div>
	<div class="separator "></div>
	<hr />
	<div class="row">
		<div class="col-md-12 text-right">
			<button class="btn btn-lg btn-primary" type="submit">
				<?=_SUBMIT?>
			</button>
		</div>
	</div>
</form>