<div class="login">
	<div class="row" style="margin: 20px 0;">
		<?=_MEMBERS_FORGOTTEN_PASS_TEXT?>
	</div>
	<form action="members/recover" method="post" class="validate-form">
		<input type="email" name="email" class="form-control required input-lg" placeholder="<?=_EMAIL?>" />
		<div class="separator sm"></div>
		<div class="row">
			<div class="col-md-5 col-sm-3">
				<?if(!empty($members_settings['captcha_on_lost_password'])) {?>
				<?=_CAPTCHA_VALIDATION_NEXT?>
				<?}?>
			</div>
			<div class="col-md-7 col-sm-3">
				<?if(!empty($members_settings['captcha_on_lost_password'])) {?>
				<?=$helper->display_catpcha()?>
				<?}?>
			</div>
		</div>
		<div class="row">
		    <div class="col-lg-8">
		        <small class="muted"><?=_MEMBERS_FORGOTTEN_MORE_HELP?></small>
		    </div>
		    <div class="col-lg-4 text-right">
		    	<hr class="d-block d-lg-none" />
		        <button class="btn btn-lg btn-primary btn-block" type="submit">
					<?=_SEND?>
				</button>
		    </div>
		</div>
	</form>
</div>