<tr id="item_<?=$item['id']?>">
	<td>
		<a href="admin.php?plugin=subscriptions&amp;op=edit&amp;id=<?=$item['id']?>"><h5><?=$helper->reduce_text($item['name'], 40)?></h5></a>
		<a href="admin.php?plugin=system&amp;file=messages&amp;op=send_message&amp;email=<?=$item['email']?>&amp;name=<?=urlencode($item['name'])?>&amp;subject=<?=urlencode('Contact from ' . $helper->config['contactname'])?>" class="send-message">
            <?=$item['email']?> <span class="icon-mail-send"></span> 
        </a>
	</td>
	<td class="no_sort hidden-phone">
		<?=$item['category']?>
	</td>
	<td class="no_sort hidden-phone">
		<?=$helper->format_sort_date($item['date'])?>
	</td>
    <td>
        <div class="navbar">
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href="#" role="button" data-toggle="dropdown"><span class="icon-menu"></span></a>
                    <ul id="actions_<?=$item['id']?>" class="dropdown-menu orders-actions" role="menu">
                        <li><a href="admin.php?plugin=system&amp;file=messages&amp;op=send_message&amp;email=<?=$item['email']?>&amp;name=<?=urlencode($item['name'])?>&amp;subject=<?=urlencode('Contact from ' . $helper->config['contactname'])?>" class="send-message"><span class="icon-mail-send left"></span> Email Subscriber</a></li>
                        <li><a href="admin.php?plugin=subscriptions&amp;op=edit&amp;id=<?=$item['id']?>"><span class="icon-pencil-3 left"></span> Edit</a></li>
                        <li><a href="admin.php?plugin=subscriptions&amp;op=delete&amp;id=<?=$item['id']?>" class="deletion" data-main-holder="main-area-for-<?=$item['id']?>"><span class="icon-remove-2 left"></span> Delete</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </td>
</tr>