<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<title><?=$pageTitle?></title>
	<meta http-equiv="content-type" content="text/html; charset=<?=$charset?>" />
	<meta name="author" content="Web Designer Express and Web Design Enterprise" />
	<meta name="rating" content="general" />
	<meta name="page-type" content="document" /> 
	<meta name="keywords" content="<?=$metaKeys?>" />
	<meta name="description" content="<?=$metaDesc?>" />
	<link href="css/style.css" rel="stylesheet" type="text/css" media="screen" />
	<script type="text/javascript" src="js/default.js"></script>
	<script type="text/javascript" src="js/jquery.js"></script>
</head>
<body style="background: #E0DDD4 url(images/bodyBG.jpg) repeat-x 0 0;">
    <div style="padding: 10px;">
        <?=$text?>
    </div>
</body>
</html>