<div class="innerPage">
	<div class="menu">
		<h1 style="color: white;"><?=$sitename?> available pages</h1>
	</div>
	<div style="padding: 20px 0 200px 0;">
				<?if($countAll) {?>
			<?foreach($pages as $page) {?>
				<div style="margin: 10px;">
					<img src="plugins/Pages/images/catsIcon.gif" /> <a href="?plugin=Pages&amp;id=<?=$page['id']?>&amp;title=<?=$page['link']?>" title="<?=$page['name']?>"><?=$page['name']?></a>
				</div>
			<?}?>
		<?}?>
	</div>
</div>