</div>
</div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-lg-2 memberside">
            <div>
                <?php require_once($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/nav_menu.php'); ?>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-8 text-center">
                    <div class="separator xs"></div>
                    <h4>Your Deals</h4>
                </div>
                <div class="col-md-4 create-deal-btn">
                    <div class="separator sm"></div>
                    <a href="members/deals/add" class="btn btn-info"><i class="icon-plus"></i> Create a Deal</a>
                </div>
            </div>
            <hr />
            <div class="separator "></div>
            <?php if(!empty($items_info)) {?>
            <div class="row">
                <?php foreach ($items_info as $item) {
                    include($_SERVER["DOCUMENT_ROOT"] . _SITE_PATH . '/plugins/members/layout/deals/layout.deals.list.phtml');
                }?>
            </div>
            <?php } else {?>
            <p>There are no deals configured yet.</p>
            <p>Click the "Create a deal" button above to fill out the form and create a new deal.</p>
            <?php }?>
            <script type="text/javascript" src="js/plugins/jquery.countdown.min.js"></script>
            <script>
                $(function(){
        $('[data-countdown]').each(function() {
            var $this = $(this), finalDate = $(this).data('countdown');
            $this.countdown(finalDate, function(event) {
                $this.html(event.strftime('<i class="icon-clock-o"></i> <strong><span> %D</span> days</strong><strong><span>%H</span> hrs</strong> <strong><span>%M</span> mins</strong> <strong><span>%S</span> secs</strong>'));
            });
        });
    });
</script>
        </div>
        <div class="col-md-2 memberside d-none d-lg-block">
            <div class="row">
                <button class="btn bg-light p-2 right-profile-img" type="button" data-toggle="collapse" data-target="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
                    <div class="row">
                        <div class="col-xl-5">
                            <img src="<?=_SITE_PATH . '/uploads/avatar/' . md5((string) $_SESSION['user_info']['id']) . '/' . $_SESSION['user_info']['avatar']?>" alt="" class="rounded-circle" />
                        </div>
                        <div class="col-xl-7 pt-2 text-ellipsis">
                            Hi, <?=$_SESSION['user_info']['first_name']?>
                        </div>
                    </div>
                </button>
            </div>
        </div>
    </div>
</div>