<div class="d-block">
    <article>
        <div class="bg-light">
            <div class="row">
                <div class="col-md-4">
                    <a href="<?=$item['url']?>">
                        <img src="<?=_SITE_PATH?>/uploads/blog/<?=$item['media']['bid']?>/<?=$item['media']['image']?>" alt="<?=$item['title']?>" class="img-fluid" />
                    </a>
                </div>
                <div class="col-md-8  p-3">
                        <h4 class="mr-3"><?=$item['title']?>
                        <a href="members/articles/delete?id=<?=$item['id']?>" class="float-right btn btn-small btn-danger  mr-3" title="DELETE">
                            <i class="icon-trash"></i>
                        </a>
                        </h4>
                        <p class="text-muted mr-3"><?=date('M d, Y', strtotime($item['date']))?> </p>
                        <a href="<?=$item['url']?>" class="float-right btn btn-small btn-<?=$item['categories']?>  mr-3">
                            Read Article
                        </a>
                        <a href="members/articles/add?id=<?=$item['id']?>" class="float-right btn btn-small btn-success  mr-3">
                            Edit Article
                        </a> 
                    </p>
                </div>
            </div>
            </a>
        </div>
    </article>
</div>