<?if(isset($_SESSION['error'])) {?>
    <div class="alert-error" title="Error">
        <?=$_SESSION['error']?>
    </div>
<?
    unset($_SESSION['error']);
}
?>
<div class="pageheader">
    <h1 class="head">
        Galleries
    </h1>
</div>
<br clear="all" />
<ul class="listfile">
                        	<li>
                            	<a class="image" href="images/preview/image1.png">
                                	<span class="img"><img src="images/thumbs/image1.png" alt="" /></span>
                                    <span class="filename">Image1.jpg</span></a>
                            </li>
                        	<li>
                            	<a class="image" href="images/preview/image2.png">
                                	<span class="img"><img src="images/thumbs/image2.png" alt="" /></span>
                                    <span class="filename">Image2.jpg</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="video" href="assets/movie1.avi">
                                	<span class="doc"><img src="images/thumbs/video.png" alt="" /></span>
                                    <span class="filename">Movie1.avi</span></a>
                            </li>
                            <li>
                            	<a class="audio" href="assets/audio1.mp3">
                                	<span class="doc"><img src="images/thumbs/audio.png" alt="" /></span>
                                    <span class="filename">Song1.mp3</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="image" href="images/preview/image3.png">
                                	<span class="img"><img src="images/thumbs/image3.png" alt="" /></span>
                                    <span class="filename">Image3.jpg</span></a>
                            </li>
                            <li>
                            	<a class="audio" href="assets/audio1.mp3">
                                	<span class="doc"><img src="images/thumbs/audio.png" alt="" /></span>
                                    <span class="filename">Song1.mp3</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                        	<li>
                            	<a class="image" href="images/preview/image5.png">
                                	<span class="img"><img src="images/thumbs/image5.png" alt="" /></span>
                                    <span class="filename">Image5.jpg</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="video" href="assets/movie1.avi">
                                	<span class="doc"><img src="images/thumbs/video.png" alt="" /></span>
                                    <span class="filename">Movie1.avi</span></a>
                            </li>
                        	<li>
                            	<a class="image" href="images/preview/image4.png">
                                	<span class="img"><img src="images/thumbs/image4.png" alt="" /></span>
                                    <span class="filename">Image4.jpg</span></a>
                            </li>
                            <li>
                            	<a class="audio" href="assets/audio1.mp3">
                                	<span class="doc"><img src="images/thumbs/audio.png" alt="" /></span>
                                    <span class="filename">Song1.mp3</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                            <li>
                            	<a class="image" href="images/preview/image6.png">
                                	<span class="img"><img src="images/thumbs/image6.png" alt="" /></span>
                                    <span class="filename">Image6.jpg</span></a>
                            </li>
                            <li>
                            	<a class="audio" href="assets/audio1.mp3">
                                	<span class="doc"><img src="images/thumbs/audio.png" alt="" /></span>
                                    <span class="filename">Song1.mp3</span></a>
                            </li>
                            <li>
                            	<a class="doc" href="assets/tutorial1.pdf">
                                	<span class="doc"><img src="images/thumbs/doc.png" alt="" /></span>
                                    <span class="filename">Tutorial1.pdf</span></a>
                            </li>
                        </ul>