<?php if(isset($_SESSION['error'])) {?>
    <div class="alert-error" title="Error">
        <?=$_SESSION['error']?>
    </div>
    <?php
    unset($_SESSION['error']);
}
?>

<div class="pageheader">
    <h1 class="head">
        Comments Management 
    </h1>
</div>
<br clear="all" />
<div class="summary-bar">
    <a href="#" class="reload tipS" title="Reload" onclick="window.location.href = window.location.href; return false;">
        <span class="icon-redo"></span>
    </a>
</div>
<div class="search-area">
    <form action="#">
        <input type="text" id="search-area" data-url="index.php?plugin=comments" value="" name="q" placeholder="Search..." />
    </form>
</div>
<div id="contentwrapper" class="contentwrapper">    
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col />
            <col style="width: 160px;" />
            <col style="width: 30px !important;"  />
        </colgroup>
        <thead>
            <tr>
                <th>Comment</th>
                <th>Information</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php
            if(count($items_info)>0)
            {
                foreach($items_info as $item)
                {
                    include($_SERVER['DOCUMENT_ROOT'] . _SITE_PATH . '/plugins/comments/admin/layout/layout.comments.list.phtml');
                }
            }
            ?>
        </tbody>
    </table>
</div>
<div id="ajax-load-more-content" class="well hide" data-url="admin.php?plugin=comments&amp;op=more">
    <img src="images/loaders/loader6.gif" alt="Loading" />
</div>