<div class="d-block">
    <article>
        <script type="application/ld+json"><?=$item['ld_json']?></script>    
        <!-- <a href="<?=$item['url']?>" style="text-decoration: none">
            <div class="blogimage" style="background-image: url(uploads/blog/<?=$item['media']['bid']?>/<?=$item['media']['image']?>)">
                <img src="<?=_SITE_PATH?>/uploads/blog/<?=$item['media']['bid']?>/<?=$item['media']['image']?>" alt="<?=$item['title']?>" class="d-none" />
                <div class="whiteBG p-3">
                 
                        <h3 class="text-center"><?=$item['title']?></h3>
                 
                    <div class="description">
                    <?php if(!empty($blog_settings['header'])) {?>
                        <?=strip_tags($helper->reduce_words($helper->filter($item['text'], 1, 1), 40))?>
                    <?php } else {?>
                        <?=strip_tags($item['text'])?>
                    <?php }?>
                    </div>
                </div>
            </div>
        </a> -->

        <div class="bg-light">
            <div class="row">
                <div class="col-md-4">
                    <a href="<?=$item['url']?>">
                        <img src="<?=_SITE_PATH?>/uploads/blog/<?=$item['media']['bid']?>/<?=$item['media']['image']?>" alt="<?=$item['title']?>" class="article-img img-fluid" />
                    </a>
                </div>
                <div class="col-md-8  p-3">
                    <a href="<?=$item['url']?>" style="text-decoration: none;">
                        <h4 class="mr-3"><?=$item['title']?></h4>
                        <div class="row">
                            <div class="col-8">
                                <p class="text-muted mr-3"><?=date('M d, Y', strtotime($item['date']))?> </p>
                            </div>
                            <div class="col-4">
                                <span class="float-right btn btn-small btn-<?=$item['categories']?>  mr-3" style="margin-top: 3px;">
                                    Read More
                                </span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            </a>
        </div>
    </article>
</div>